version: '3.1'
services:
  database:
    image: postgres:10.5-alpine
    container_name: wild-adventure
    restart: always
    hostname: 127.0.0.1
    volumes:
      - ./database/:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=wild-adventure
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
